gsql ./bi/bi_1.gsql
gsql ./bi/bi_2.gsql
gsql ./bi/bi_3.gsql
gsql ./bi/bi_4.gsql
gsql ./bi/bi_5.gsql
gsql ./bi/bi_6.gsql
gsql ./bi/bi_7.gsql
gsql ./bi/bi_8.gsql
gsql ./bi/bi_9.gsql
gsql ./bi/bi_10.gsql
gsql ./bi/bi_11.gsql
gsql ./bi/bi_12.gsql
gsql ./bi/bi_13.gsql
gsql ./bi/bi_14.gsql
gsql ./bi/bi_15.gsql
gsql ./bi/bi_16.gsql
gsql ./bi/bi_17.gsql
gsql ./bi/bi_18.gsql
gsql ./bi/bi_19.gsql
gsql ./bi/bi_20.gsql
gsql ./bi/bi_21.gsql
gsql ./bi/bi_22.gsql
gsql ./bi/bi_23.gsql
gsql ./bi/bi_24.gsql
gsql ./bi/bi_25.gsql
